services:
  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./src/backend:/app/src/backend

  frontend:
    build:
      context: src/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    depends_on:
      - backend
